name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  deps:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

  build:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Start agents
        run: yarn nx-cloud start-ci-run

      - name: Build projects
        run: yarn nx run-many --target=build --all=true --parallel=true

      - name: Upload dist artifacts
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy-docs:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download dist folder
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist

      - name: Deploy to pinata
        run: yarn dlx ipfs-deploy dist/apps/docs -p pinata -d cloudflare
        env:
          IPFS_DEPLOY_CLOUDFLARE__API_TOKEN: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__API_TOKEN }}
          IPFS_DEPLOY_CLOUDFLARE__ZONE: ${{ secrets.IPFS_DEPLOY_CLOUDFLARE__ZONE }}
          IPFS_DEPLOY_CLOUDFLARE__RECORD: '_dnslink.docs.humor-pass.mdellamea.it'
          IPFS_DEPLOY_PINATA__API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__API_KEY }}
          IPFS_DEPLOY_PINATA__SECRET_API_KEY: ${{ secrets.IPFS_DEPLOY_PINATA__SECRET_API_KEY }}
