name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

  agents:
    needs: deps
    runs-on: ubuntu-latest
    name: Agents
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent

  build:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn

      - name: Install dependencies
        run: yarn

      - name: Start agents
        run: yarn nx-cloud start-ci-run

      - name: Build projects
        run: yarn nx affected --target build --parallel --max-parallels=3

      - name: Stop all agents
        run: yarn nx-cloud stop-all-agents

  if-fails:
    needs: [deps, build]
    if: always() && (needs.build.result == 'failure')
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.0
        with:
          node-version: 14
          cache: yarn
      - name: Stop all agents
        run: yarn nx-cloud stop-all-agents
